/**
 * core/types — 核心游戏类型定义
 *
 * 包含构成游戏基础的所有领域类型：
 * 属性系统（CharacterStats、BaseStats、GrowthStats、AttributeDefinition、CoreStatKey）、
 * 品质系统（Quality）、世界类型（WorldType）、
 * 主角（Protagonist）、物品、装备、功法等核心接口。
 */

// 基础类型（types.ts）
export type {
  // 属性系统（旧 — deprecated）
  BaseStats,
  GrowthStats,
  CharacterStats,
  StatKey,
  FlatStats,
  StatName,
  StatImpact,
  ImpactfulTrait,
  // 属性系统（新 — Attribute/CoreStat 解耦）
  AttributeCategory,
  AttributeCalculation,
  AttributeEnumValue,
  AttributeTemplate,
  NumericAttributeTemplate,
  EnumAttributeTemplate,
  AttributeGrowthTerm,
  AttributeGrowthRule,
  WorldviewAttributeConfig,
  // 兼容别名
  AttributeDefinition,
  NumericAttributeDefinition,
  EnumAttributeDefinition,
  CoreStatKey,
  CoreStatBaseValues,
  SpecialResourceDef,
  CharacterAttributesV3,
  // 种族与天赋
  RaceDefinition,
  InnateAbility,
  TalentEffect,
  TalentRarity,
  TalentDefinition,
  // 对话检定
  DialogueCheck,
  CheckResult,
  // 角色
  Character,
  DimensionScores,
  RoleArchetype,
  RoleProfile,
  SynergyEffect,
  CharacterEvaluation,
  // 世界
  ExtensibleWorldType,
  WorldType,
  WorldDifficulty,
  WorldImpact,
  WorldFaction,
  World,
  WorldBalanceStats,
  // 品质
  Quality,
  ImpactLevel,
  // 物品/道具
  ItemType,
  ItemRarity,
  EffectType,
  ItemEffect,
  ItemDefinition,
  InventoryItem,
  ActiveEffect,
  // 战斗
  BattleLog,
  BattleState,
  ActiveBattleState,
  EnemyTier,
  // 主角
  Protagonist,
  CultivationPath,
  PlayerCurrencies,
  // 功法
  TechniqueType,
  Technique,
  // 装备
  EquipmentSlot,
  Equipment,
  UpgradeableItemType,
  UpgradeMaterial,
  // 修炼
  GamePhase,
  CultivationResult,
  StatChanges,
  EventChoice,
  AdventureEvent,
  CellType,
  AdventureCell,
  DungeonConfig,
  BattleResult,
  MessageRecord,
  ActionResult,
  ActionTab,
  AdventurePhase,
  CraftingState,
  ForgingState,
  AdventureSessionState,
  GameState,
  // 成就
  AchievementType,
  AchievementStatus,
  AchievementDefinition,
  // 图鉴
  BondType,
  BondLevel,
  BondReward,
  BondDefinition,
  CollectionStatus,
  CollectionEntry,
  // 统计
  GameStatistics,
} from './types';

export {
  getFinalStats,
  getStatKeys,
  createDefaultStats,
  fromOldStats,
  createStatsWithBonuses,
  updateGrowthStats,
  updateBaseStats,
  getGrowthStatCap,
  clampGrowthStatValue,
  createDefaultCharacterStats,
  QualityNames,
  EquipmentSlotNames,
  EquipmentSlotEffect,
  TECHNIQUE_SLOT_COUNT,
  UPGRADE_CONFIG,
  MESSAGE_CONFIG,
  DEFAULT_STATISTICS,
  createInventoryItem,
  migrateInventoryItem,
  getBuiltinWorldTypes,
} from './types';

// 扩展类型（typesExtension.ts）
export type {
  CultivationPathProgress,
  BottleneckType,
  RealmBottleneck,
  BottleneckRequirements,
  TribulationConfig,
  TribulationState,
  MentalState,
  MentalBuff,
  DemonEncounter,
  DemonChoice,
  ProficiencyLevel,
  TechniqueProficiency,
  TechniqueEssence,
  EssenceEffect,
  AffixType,
  EquipmentAffix,
  AffixEffect,
  EquipmentEnhancement,
  ReputationLevel,
  TaskProgress,
  TaskRoundState,
  CommissionProgress,
  CommissionState,
  FactionProgress,
  CurrencyType,
  CurrencyState,
  TitleProgress,
  ChoiceImpact,
  Consequence,
  ProtagonistExtension,
  TechniqueExtension,
  EquipmentExtension,
  AscensionMark,
  WorldVisitRecord,
  AscensionRecord,
  GuardianBattleState,
  AscensionChallengeResult,
  NewWorldInfo,
  InheritanceChoice,
  DiscoveredWorld,
  AscensionFlowState,
  DeathCause,
  DeathState,
  CriticalHealthLevel,
  CriticalHealthState,
  GameStatistics as ExtendedGameStatistics,
} from './typesExtension';

export {
  createDefaultDailyRoundState,
  createDefaultWeeklyRoundState,
  createDefaultCommissionState,
  createDefaultFactionProgress,
  DEFAULT_PROTAGONIST_EXTENSION,
  DEFAULT_TECHNIQUE_EXTENSION,
  DEFAULT_EQUIPMENT_EXTENSION,
  migrateProtagonist,
  migrateTechnique,
  migrateEquipment,
  DEFAULT_ASCENSION_MARK,
  DEFAULT_GUARDIAN_BATTLE_STATE,
  DEFAULT_ASCENSION_FLOW_STATE,
  DEFAULT_DEATH_STATE,
  getCriticalHealthLevel,
  getCriticalHealthEffect,
  getDeathMessage,
} from './typesExtension';
